spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpdasemA
    username: user
    password: heslo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 2024
  servlet:
    context-path: /api